In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
lego = pd.read_csv("lego_sets_and_themes.csv")

In [8]:
lego.head()

,set_number,set_name,year_released,number_of_parts,image_url,theme_name
0,001-1,Gears,1965.0,43.0,https://cdn.rebrickable.com/media/sets/001-1.jpg,Technic
1,002-1,4.5V Samsonite Gears Motor Set,1965.0,3.0,https://cdn.rebrickable.com/media/sets/002-1.jpg,Technic
2,1030-1,TECHNIC I: Simple Machines Set,1985.0,210.0,https://cdn.rebrickable.com/media/sets/1030-1.jpg,Technic
3,1038-1,ERBIE the Robo-Car,1985.0,120.0,https://cdn.rebrickable.com/media/sets/1038-1.jpg,Technic
4,1039-1,Manual Control Set 1,1986.0,39.0,https://cdn.rebrickable.com/media/sets/1039-1.jpg,Technic

In [4]:
lego.shape

(21503, 6)

In [11]:
lego.columns

Index(['set_number', 'set_name', 'year_released', 'number_of_parts',
       'image_url', 'theme_name'],
      dtype='str')

In [5]:
lego.dtypes

set_number             str
set_name               str
year_released      float64
number_of_parts    float64
image_url              str
theme_name             str
dtype: object

In [6]:
lego.describe()

       year_released  number_of_parts
count   21496.000000     21496.000000
mean     2007.579782       162.461760
std        13.980685       417.187521
min      1949.000000         0.000000
25%      2001.000000         4.000000
50%      2012.000000        32.000000
75%      2018.000000       142.000000
max      2023.000000     11695.000000

In [12]:
lego.isnull().sum()

set_number         7
set_name           7
year_released      7
number_of_parts    7
image_url          7
theme_name         0
dtype: int64

In [18]:
(lego["number_of_parts"] == 0).sum()

np.int64(4384)

In [14]:
lego.duplicated().sum()

np.int64(0)

In [15]:
lego["set_number"].duplicated().sum()

np.int64(6)

In [22]:
lego["theme_name"].nunique()

383